services:
  main_service:
    build:
      context: ./
      dockerfile: Dockerfile

    container_name: rag_service
    #privileged: true
    #restart: unless-stopped
    ports:

    - "0.0.0.0:6000:6000"
    - "0.0.0.0:8585:8585"
    - "0.0.0.0:8000:8000"

    #restart: unless-stopped

    volumes:
      - ./:/opt/


  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

